apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels: 
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend:v3
        ports:
        - containerPort: 8000
        env:
        - name: db_user
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-user
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-password
        - name: db_host
          value: database-service
---

apiVersion: v1
kind: Service # service type defaults to clusterIP
metadata:
  name: backend-service
spec: 
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

