apiVersion: v1
data:
  default.conf: "server {\r\n    listen 80;\r\n\r\n    location / {\r\n        root
    /usr/share/nginx/html;\r\n        index index.html;\r\n    }\r\n\r\n    location
    /api/ {\r\n        proxy_pass http://backend-service:8000/;\r\n    }\r\n}"
kind: ConfigMap
metadata:
  name: config
